
version: 2

sources:
  - name: jaffle_shop             #name you will use to refer to this source in dbt
    database: dbt-demo-guideline  #name of your GCP project
    schema: raw_data              #name of your BigQuery dataset

    tables:
      - name: customers           #name of your BigQuery table
      - name: orders              #name of your BigQuery table

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
